import React from 'react';
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  renderToStream,
  Font,
} from '@react-pdf/renderer';
import { ResearchResult } from './types';

// Register fonts if needed, or use standard fonts
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/Roboto-Regular.ttf' });

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2px solid #3b82f6',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e3a8a',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
  },
  section: {
    margin: 10,
    padding: 10,
  },
  heading: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#334155',
    backgroundColor: '#f1f5f9',
    padding: 5,
    borderRadius: 4,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 10,
    color: '#0f172a',
    textAlign: 'justify',
  },
  bulletPoint: {
    fontSize: 11,
    lineHeight: 1.5,
    marginLeft: 15,
    marginBottom: 5,
    color: '#334155',
  },
  sourceContainer: {
    marginTop: 30,
    borderTop: '1px solid #e2e8f0',
    paddingTop: 10,
  },
  sourceTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#475569',
    marginBottom: 5,
  },
  sourceLink: {
    fontSize: 10,
    color: '#2563eb',
    marginBottom: 3,
    textDecoration: 'none',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 10,
    color: '#94a3b8',
    textAlign: 'center',
    borderTop: '1px solid #e2e8f0',
    paddingTop: 10,
  },
});

const ResearchDocument = ({ result }: { result: ResearchResult }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{result.title}</Text>
        <Text style={styles.subtitle}>
          Generated by AI Research Tool • {new Date().toLocaleDateString()}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>Executive Summary</Text>
        <Text style={styles.text}>{result.summary}</Text>
      </View>

      {result.keyPoints && result.keyPoints.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.heading}>Key Findings</Text>
          {result.keyPoints.map((point, i) => (
            <Text key={i} style={styles.bulletPoint}>
              • {point}
            </Text>
          ))}
        </View>
      )}

      <View style={styles.section}>
        <Text style={styles.heading}>Detailed Analysis</Text>
        <Text style={styles.text}>{result.content}</Text>
      </View>

      <View style={styles.section}>
        <View style={styles.sourceContainer}>
          <Text style={styles.sourceTitle}>References & Sources</Text>
          {result.sources.map((source, i) => (
            <Text key={i} style={styles.sourceLink}>
              [{i + 1}] {source.title} - {source.link}
            </Text>
          ))}
        </View>
      </View>

      <Text
        style={styles.footer}
        render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
        fixed
      />
    </Page>
  </Document>
);

export async function generatePDFStream(
  result: ResearchResult
): Promise<NodeJS.ReadableStream> {
  const stream = await renderToStream(<ResearchDocument result={result} />);
  return stream;
}
